Evaluaciones Tecnicas/Controllers/Preguntas y Respuestas/MultipleChoiceController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones.Controllers
{
    //[Authorize(Roles = "Administrador,CreadorPreguntas")]//para entrar en admin debe estar logueado y  asignarle el rol

    public class MultipleChoiceController : Controller
    {
        // GET: MultipleChoice
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Index(int Id)
        {

            MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();
           
                return View(multipleChoiceComponent.listaRespuestaMultipleChoiceAlAzar(Id));


        }

        // GET: MultipleChoice/Details/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Details(int id)
        {
            MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();

            return View(multipleChoiceComponent.ReadBy(id));
        }

        // GET: MultipleChoice/Create
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Create(int id)
        {
            MultipleChoice multipleChoice = new MultipleChoice();
            PreguntaComponent preguntaComponent = new PreguntaComponent();
            Pregunta pregunta = new Pregunta();
            pregunta = preguntaComponent.ReadBy(id);

            multipleChoice.pregunta = pregunta;
           
            return View(multipleChoice);
        }

        // POST: MultipleChoice/Create
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                MultipleChoice multipleChoice = new MultipleChoice();
                if (collection.Get("correcta").Count()==10)
                {
                    multipleChoice.Correcta = true;
                }
                else
                {
                    multipleChoice.Correcta = false;
                }
          
                multipleChoice.LaRespuesta = collection.Get("LaRespuesta");
                multipleChoice.pregunta.Id = int.Parse(collection.Get("pregunta.Id"));
                MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();
                multipleChoiceComponent.Create(multipleChoice);

                return RedirectToAction("Index",new { id = multipleChoice.pregunta.Id });
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: MultipleChoice/Edit/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Edit(int id)
        {
            MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();

            return View(multipleChoiceComponent.ReadBy(id));
        }

        // POST: MultipleChoice/Edit/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                MultipleChoice multipleChoice = new MultipleChoice();
                multipleChoice.Id = id;

                if (collection.Get("Correcta").Count() == 10)
                {
                    multipleChoice.Correcta = true;
                }
                else
                {
                    multipleChoice.Correcta = false;
                }
                multipleChoice.LaRespuesta = collection.Get("LaRespuesta");
                multipleChoice.pregunta.Id = int.Parse(collection.Get("pregunta.Id")); 
                MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();
                multipleChoiceComponent.Update(multipleChoice);

                return RedirectToAction("Index", new { id = multipleChoice.pregunta.Id });
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // GET: MultipleChoice/Delete/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Delete(int id)
        {
            MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();

            return View(multipleChoiceComponent.ReadBy(id));
        }

        // POST: MultipleChoice/Delete/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                MultipleChoiceComponent multipleChoiceComponent = new MultipleChoiceComponent();
                multipleChoiceComponent.Delete(id);
                return RedirectToAction("Index", new { id = int.Parse(collection.Get("pregunta.Id")) });
            }
            catch (Exception e)
            {
                return View();
            }
        }
    }
}

Evaluaciones Tecnicas/Views/MultipleChoice/Create.cshtml
@model Entities.MultipleChoice

@{
    ViewBag.Title = "Index";
    string layout = "~/Views/Shared/" + Session["Layout"] + ".cshtml";
    Layout = layout;
}


<link href="~/Content/modern-business.css" rel="stylesheet" />
@Html.HiddenFor(model => model.pregunta.Id)

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Crear una respuesta para la pregunta <i>"@Html.DisplayFor(model => model.pregunta.LaPregunta)"</i></h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.pregunta.Id)

                    <h5 class="text-justify">Respuesta</h5>
                    @Html.EditorFor(model => model.LaRespuesta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LaRespuesta, "", new { @class = "text-danger" })
                    <br />


                    <h5 class="text-justify">¿Es correcta?</h5>
                    @Html.CheckBoxFor(model => model.Correcta)
                    @Html.ValidationMessageFor(model => model.Correcta, "", new { @class = "text-danger" })

                </div>


                <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "MultipleChoice",new { id = Model.pregunta.Id })'" />

                <br />

                <input type="submit" value="Crear" class="btn btn-outline-info" />

            </div>
        </div>
    </div>
}

@section scripts
{
}

Evaluaciones Tecnicas/Views/MultipleChoice/Delete.cshtml
@model Entities.MultipleChoice

@{
    ViewBag.Title = "Index";
    string layout = "~/Views/Shared/" + Session["Layout"] + ".cshtml";
    Layout = layout;
}


<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar la respuesta  <i>"@Html.DisplayFor(model => model.LaRespuesta)"</i>?</h3>

    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="col-md-10">


            @Html.EditorFor(model => model.pregunta.Id, new { htmlAttributes = new { @readonly = "readonly", @style = "display: none;" } })
            @Html.ValidationMessageFor(model => model.pregunta.Id, "", new { @class = "text-danger" })
            <br />
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-outline-info" />

            <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "MultipleChoice",new { id = Model.pregunta.Id })'" />
        </div>




    }
</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/MultipleChoice/Details.cshtml
@model Entities.MultipleChoice

@{
    ViewBag.Title = "Index";
    string layout = "~/Views/Shared/" + Session["Layout"] + ".cshtml";
    Layout = layout;
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div class="table-responsive col-md-12">
    @Html.HiddenFor(Model => Model.pregunta.Id)
    <h4>Detalles de la respuesta </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pregunta.LaPregunta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pregunta.LaPregunta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LaRespuesta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaRespuesta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correcta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correcta)
        </dd>

    </dl>

    <div> <h5> @Html.ActionLink("Editar", "Edit", new { id = Model.Id })</h5></div>
    <div>

        <input type="button" class="BotonVerde " style="float:left" value="Volver" onclick="location.href='@Url.Action("Index", "MultipleChoice",new { id = Model.pregunta.Id })'" />
    </div>
</div>


@section scripts
{
}

Evaluaciones Tecnicas/Views/MultipleChoice/Edit.cshtml
@model Entities.MultipleChoice

@{
    ViewBag.Title = "Index";
    string layout = "~/Views/Shared/" + Session["Layout"] + ".cshtml";
    Layout = layout;
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4">

                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Editar la respuesta @Html.DisplayFor(model => model.respuestas)</h6>

                </div>

                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)






                    <h5 class="text-justify">Respuesta</h5>
                    @Html.EditorFor(model => model.LaRespuesta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LaRespuesta, "", new { @class = "text-danger" })


                    <h5 class="text-justify">Respuesta</h5>
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Correcta)
                        @Html.ValidationMessageFor(model => model.Correcta, "", new { @class = "text-danger" })
                    </div>

                    <h5 class="text-justify">Numero de Pregunta</h5>

                    @Html.EditorFor(model => model.pregunta.Id, new { htmlAttributes = new { @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.pregunta.Id, "", new { @class = "text-danger" })


                </div>



                <input type="button" class="btn btn-outline-primary " style="float:left" value="Volver" onclick="location.href='@Url.Action("Index", "MultipleChoice",new { id = Model.pregunta.Id })'" />
                <br />
                <input type="submit" value="Guardar" class="btn btn-outline-info" />
            </div>
        </div>
    </div>
}
@section scripts
{
}

Evaluaciones Tecnicas/Views/MultipleChoice/Index.cshtml
@model Entities.MultipleChoice

@{
    ViewBag.Title = "Index";
    string layout = "~/Views/Shared/" + Session["Layout"] + ".cshtml";
    Layout = layout;
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de respuestas de <i>  "@Html.DisplayFor(model => model.pregunta.LaPregunta)"</i></h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Respuesta</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">¿Es Correcta?</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model.ListaMultipleChoice)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.LaRespuesta)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Correcta)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Editar", "Edit", new { id = int.Parse(item.Id.ToString()) }) |

                                                    @Html.ActionLink("Eliminar", "Delete", new { id = int.Parse(item.Id.ToString()) }) |

                                                </td>


                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                            <input type="button" class="btn btn-outline-primary " style="float:left" value="Crear" onclick="location.href='@Url.Action("Create", "MultipleChoice", new { id =Model.pregunta.Id })'" />
                            <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "PreguntaCategoria")'" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

@section scripts
{
}