Evaluaciones Tecnicas/Controllers/Preguntas y Respuestas/CategoriaController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones.Controllers
{
    //[Authorize(Roles = "Administrador")]//para entrar en admin debe estar logueado y  asignarle el rol

    public class CategoriaController : Controller
    {
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult SaludTipoPregunta(int id)
        {
            SaludCategoriaComponent saludCategoriaComponent = new SaludCategoriaComponent(id);
            SaludCategoria salud = new SaludCategoria();
            salud = saludCategoriaComponent.verificarSaludTipoPregunta();
            salud.CantidadDePreguntasBuenaSalud = saludCategoriaComponent.CantidadPreguntaConBuenaSalud();
            return View(salud);


        }
        // GET: Categoria
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Index()
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.Read());
        }
        // GET: Categoria
        [AuthorizerUser(_roles: "RRHH")]
        public ActionResult IndexRRHH()
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.Read());
        }

        // GET: Categoria/Details/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Details(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                Categoria categoria = new Categoria();
                categoria.LaCategoria= collection.Get("LaCategoria");
                categoria.Descripcion = collection.Get("Descripcion");
                categoriaComponent.Create(categoria);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categoria/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Edit(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // POST: Categoria/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                Categoria categoria = new Categoria();
                categoria.Id = id;
                categoria.LaCategoria = collection.Get("LaCategoria");
                categoria.Descripcion = collection.Get("Descripcion");
                categoriaComponent.Update(categoria);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categoria/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // POST: Categoria/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                categoriaComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Evaluaciones Tecnicas/Controllers/Servicios/RolesController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Index()
        {
            RolesComponent roles = new RolesComponent();
            return View(roles.Read());
        }

        // GET: Roles/Details/5
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Details(int id)
        {
            RolesComponent roles = new RolesComponent();
            return View(roles.ReadBy(id));
        }

        // GET: Roles/Create
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                roles.name = collection.Get("name");
                rolesComponent.Create(roles);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Roles/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Edit(int id)
        {
            RolesComponent rolesComponent = new RolesComponent();
            return View(rolesComponent.ReadBy(id));
        }

        // POST: Roles/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                RolesComponent rolesComponent = new RolesComponent();
                Roles roles = new Roles();
                roles.name = collection.Get("name");
                roles.id = id;
                rolesComponent.Update(roles);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Roles/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id)
        {

            RolesComponent rolesComponent = new RolesComponent();
            return View(rolesComponent.ReadBy(id));
        }

        // POST: Roles/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                RolesComponent rolesComponent = new RolesComponent();
                rolesComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Evaluaciones Tecnicas/Views/Categoria/Create.cshtml
@model Entities.Categoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4 " style="min-width:250%">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Crear una Categoria</h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <h5 class="text-justify">Categoria</h5>
                    @Html.EditorFor(model => model.LaCategoria, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LaCategoria, "", new { @class = "text-danger" })

                    <br />
                    <h5 class="text-justify">Descripción</h5>
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })


                </div>


                <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "Categoria")'" />

                <br />

                <input type="submit" value="Crear" class="btn btn-outline-info" />

            </div>
        </div>
    </div>
}

@section scripts
{
}

Evaluaciones Tecnicas/Views/Categoria/Delete.cshtml
@model Entities.Categoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div>
    <h3>¿Esta seguro de eliminar @Html.DisplayFor(model => model.LaCategoria)?</h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-outline-info" />

            <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "Roles")'" />
        </div>
    }
</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/Categoria/Edit.cshtml
@model Entities.Categoria

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()




    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4 " style="min-width:250%">

                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Editar el Rol @Html.DisplayFor(model => model.LaCategoria)</h6>

                </div>

                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)





                    <h5 class="text-justify">Categoria</h5>
                    @Html.EditorFor(model => model.LaCategoria, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LaCategoria, "", new { @class = "text-danger" })
                    <br />


                    <h5 class="text-justify">Descripción</h5>
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })

                </div>



                <input type="button" class="btn btn-outline-primary " style="float:left" value="Volver" onclick="location.href='@Url.Action("Index", "Categoria")'" />
                <br />
                <input type="submit" value="Guardar" class="btn btn-outline-info" />
            </div>
        </div>
    </div>
}

@section scripts
{
}

Evaluaciones Tecnicas/Views/Categoria/Index.cshtml
@model IEnumerable<Entities.Categoria>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de categorias</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Categoria</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Descripcion</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.LaCategoria)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Editar", "Edit", new { id = int.Parse(item.Id.ToString()) }) |

                                                    @Html.ActionLink("Eliminar", "Delete", new { id = int.Parse(item.Id.ToString()) }) |
                                                    @Html.ActionLink("Salud", "SaludTipoPregunta", new { id = int.Parse(item.Id.ToString()) }) |



                                                </td>


                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="button" class="btn btn-outline-primary " style="float:right" value="Crear" onclick="location.href='@Url.Action("create", "Categoria")'" />
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>


@section scripts
{
}

Evaluaciones Tecnicas/Views/Categoria/IndexRRHH.cshtml
@model IEnumerable<Entities.Categoria>

@{
    ViewBag.Title = "IndexRRHH";
    Layout = "~/Views/Shared/_LayoutRRHH.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de categorias</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Categoria</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Descripcion</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.LaCategoria)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                                </td>
                                                <td>
                                                   
                                                    @Html.ActionLink("Salud", "SaludTipoPregunta", new { id = int.Parse(item.Id.ToString()) })



                                                </td>


                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                 
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>


@section scripts
{
}

Evaluaciones Tecnicas/Views/Categoria/SaludTipoPregunta.cshtml
@model Entities.SaludCategoria

@{
    ViewBag.Title = "SaludTipoPregunta";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}




<link href="~/Content/modern-business.css" rel="stylesheet" />
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">
        <div class="d-flex flex-column" style="align-content:center">
            <div class="container-fluid">
                <div class="card shadow mb-4 ">
                    <div class=" card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">
                            Salud de la Categoria
                            @foreach (var item in Model.ListaPreguntasTotal)
                            {
                                <i> "@Html.DisplayFor(modelItem => item.Pregunta.categoria.LaCategoria)"</i>
                                break;
                            }

                        </h6>



                    </div>
                    <div class="card-body">

                        <dl class="dl-horizontal">




                            <dt>
                                @Html.DisplayNameFor(model => model.SaludCategtoria)
                                <i style="text-decoration:none">&nbsp</i>

                                @if (Model.SaludCategtoria == true)
                                {
                                    <a href="#" class="btn btn-success btn-circle">
                                        <i class="fas fa-check"></i>
                                    </a>
                                }
                                @if (Model.SaludCategtoria == false)
                                {
                                    <a href="#" class="btn btn-danger btn-circle">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                }
                            </dt>
                            <dt style="color:black ; font-size:30px"> Analisis de la pregunta:</dt>

                            &nbsp
                            &nbsp

                            <dt>
                                1.  @Html.DisplayNameFor(model => model.TieneMasDe20Preguntas)
                                <i style="text-decoration:none">&nbsp</i>

                                @if (Model.TieneMasDe20Preguntas == true)
                                {
                                    <a href="#" class="btn btn-success btn-circle">
                                        <i class="fas fa-check"></i>
                                    </a>
                                }
                                @if (Model.TieneMasDe20Preguntas == false)
                                {
                                    <a href="#" class="btn btn-danger btn-circle">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                }
                            </dt>
                            &nbsp
                            <dt>
                                2.   @Html.DisplayNameFor(model => model.TieneMasDe20PreguntasConBuenaSalud)
                                &nbsp


                                @if (Model.TieneMasDe20PreguntasConBuenaSalud == true)
                                {
                                    <a href="#" class="btn btn-success btn-circle">
                                        <i class="fas fa-check"></i>
                                    </a>
                                }
                                @if (Model.TieneMasDe20PreguntasConBuenaSalud == false)
                                {
                                    <a href="#" class="btn btn-danger btn-circle">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                }
                            </dt>
                            &nbsp
                            &nbsp
                            <dt>

                                3.   @Html.DisplayNameFor(model => model.CantidadDePreguntas)


                                @Html.DisplayFor(model => model.CantidadDePreguntas)

                            </dt>
                            &nbsp
                            &nbsp

                            <dt>

                                4.   @Html.DisplayNameFor(model => model.nivelBajo)


                                @Html.DisplayFor(model => model.nivelBajo)

                            </dt>
                            &nbsp
                            &nbsp
                            <dt>
                                5.   @Html.DisplayNameFor(model => model.nivelMedio)


                                @Html.DisplayFor(model => model.nivelMedio)

                            </dt>
                            &nbsp
                            &nbsp
                            <dt>
                                6.   @Html.DisplayNameFor(model => model.nivelAlto)


                                @Html.DisplayFor(model => model.nivelAlto)

                            </dt>
                            &nbsp
                            &nbsp
                            <dt>
                                7.   @Html.DisplayNameFor(model => model.CantidadDePreguntasBuenaSalud):


                                @Html.DisplayFor(model => model.CantidadDePreguntasBuenaSalud)
                            </dt>

                        </dl>



                    </div>





                </div>
            </div>
        </div>

        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de roles</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Pregunta</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">¿Se puede utilizar?</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model.ListaPreguntasTotal)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Pregunta.LaPregunta)
                                                </td>
                                                <td class="sorting_1" style="text-align:center">
                                                    @if (item.SaludCategtoria == true)
                                                    {
                                                        <a href="#" class="btn btn-success btn-circle">
                                                            <i class="fas fa-check"></i>
                                                        </a>
                                                    }
                                                    @if (item.SaludCategtoria == false)
                                                    {
                                                        <a href="#" class="btn btn-danger btn-circle">
                                                            <i class="fas fa-cross"></i>
                                                        </a>
                                                    }
                                                </td>

                                                <td>
                                                    @if (item.Pregunta.tipoPregunta.TipoDePregunta == "MultipleChoice")
                                                    {
                                                        @Html.ActionLink("Salud Pregunta", "SaludMultipleChoice", "SaludPregunta", new { id = item.Pregunta.Id }, null)
                                                    }

                                                    @if (item.Pregunta.tipoPregunta.TipoDePregunta == "Ordenado")
                                                    {
                                                        @Html.ActionLink("Salud Pregunta", "SaludOrdenado", "SaludPregunta", new { id = item.Pregunta.Id }, null)
                                                    }
                                                    @if (item.Pregunta.tipoPregunta.TipoDePregunta == "MultipleChoiceCompuesto")
                                                    {
                                                        @Html.ActionLink("Salud Pregunta", "SaludMultipleChoiceCompuesto", "SaludPregunta", new { id = item.Pregunta.Id }, null)
                                                    }
                                                </td>


                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

@section scripts
{
}