Evaluaciones Tecnicas/Controllers/Preguntas y Respuestas/CategoriaController.cs
using Entities;
using Evaluaciones_Tecnicas.Filter;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluaciones.Controllers
{
    //[Authorize(Roles = "Administrador")]//para entrar en admin debe estar logueado y  asignarle el rol

    public class CategoriaController : Controller
    {
        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult SaludTipoPregunta(int id)
        {
            SaludCategoriaComponent saludCategoriaComponent = new SaludCategoriaComponent(id);
            SaludCategoria salud = new SaludCategoria();
            salud = saludCategoriaComponent.verificarSaludTipoPregunta();
            salud.CantidadDePreguntasBuenaSalud = saludCategoriaComponent.CantidadPreguntaConBuenaSalud();
            return View(salud);


        }
        // GET: Categoria
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Index()
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.Read());
        }
        // GET: Categoria
        [AuthorizerUser(_roles: "RRHH")]
        public ActionResult IndexRRHH()
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.Read());
        }

        // GET: Categoria/Details/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Details(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                Categoria categoria = new Categoria();
                categoria.LaCategoria= collection.Get("LaCategoria");
                categoria.Descripcion = collection.Get("Descripcion");
                categoriaComponent.Create(categoria);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categoria/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Edit(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // POST: Categoria/Edit/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                Categoria categoria = new Categoria();
                categoria.Id = id;
                categoria.LaCategoria = collection.Get("LaCategoria");
                categoria.Descripcion = collection.Get("Descripcion");
                categoriaComponent.Update(categoria);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categoria/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        public ActionResult Delete(int id)
        {
            CategoriaComponent categoriaComponent = new CategoriaComponent();

            return View(categoriaComponent.ReadBy(id));
        }

        // POST: Categoria/Delete/5
        [AuthorizerUser(_roles: "Administrador")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                CategoriaComponent categoriaComponent = new CategoriaComponent();
                categoriaComponent.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Evaluaciones Tecnicas/Controllers/Preguntas y Respuestas/PreguntaCategoriaController.cs
using Evaluaciones.Models;
using Entities;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Evaluaciones_Tecnicas.Filter;

namespace Evaluaciones.Controllers
{
  
    public class PreguntaCategoriaController : Controller
    {



        // GET: PreguntaCategoria

        [AuthorizerUser(_roles: "Administrador,RRHH")]
        public ActionResult Index(string Pregunta, string Categoria, string preguntaParcial)
        {
            
           
            ViewBag.categoriaLista = new SelectList(CategoriaModels.ListCategoriaOrdenada(), "Id", "LaCategoria");

            ViewBag.categoriaPregunta = new SelectList(PreguntaModels.ListCategoriaOrdenada(), "Id", "LaPregunta");



            PreguntaCategoriaModels preguntaCategoriaModels = new PreguntaCategoriaModels();
           
           
                return View(preguntaCategoriaModels.Buscar(Pregunta, Categoria, preguntaParcial));
           

           
           

            
          
        }


        [AuthorizerUser(_roles: "Administrador,RRHH")]
        // GET: PreguntaCategoria/Details/5
        public ActionResult Categoria(Int16 id)
        {
            PreguntaCategoriaModels preguntaCategoriaModels = new PreguntaCategoriaModels();
      
            return View(preguntaCategoriaModels.Read(id));
        }



        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // GET: PreguntaCategoria/Create
        public ActionResult Create( int id)
        {
            PreguntaCategoriaModels preguntaCategoriaModels = new PreguntaCategoriaModels();
            PreguntaCategoriaModels result = new PreguntaCategoriaModels();
          result=  preguntaCategoriaModels.ObtenerCategoria(id);

            #region Categoria
            
            result.categorias.Select(y =>
                                new
                                {
                                    Id = y.Id,
                                    LaCategoria = y.LaCategoria
                                });

            ViewBag.categoriaLista = new SelectList(result.categorias, "Id", "LaCategoria");


            #endregion
            return View(result);
        }


        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // POST: PreguntaCategoria/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                PreguntaCategoriaComponent preguntaCategoriaComponent = new PreguntaCategoriaComponent();

                PreguntaCategoria preguntaCategoria = new PreguntaCategoria();
                if (collection.Count >1)
                {
                    preguntaCategoria.Categorias.Id = int.Parse(collection.Get("Categoria"));
                    preguntaCategoria.Pregunta.Id = int.Parse(collection.Get("ID_Pregunta"));
                    preguntaCategoriaComponent.Create(preguntaCategoria);
                }
                
               
               

                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // GET: PreguntaCategoria/Edit/5
        public ActionResult Edit(int id)
        {

         
            return View();
        }


        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // POST: PreguntaCategoria/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // GET: PreguntaCategoria/Delete/5
        public ActionResult Delete(int Id_categoria, int Id_Pregunta)
        {
            PreguntaCategoria preguntaCategoria = new PreguntaCategoria(Id_categoria, Id_Pregunta);
            PreguntaCategoriaComponent preguntaCategoriaComponent = new PreguntaCategoriaComponent();


            return View(preguntaCategoriaComponent.ReadBy(preguntaCategoria));
        }


        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        // POST: PreguntaCategoria/Delete/5
        [HttpPost]
        public ActionResult Delete(int Id_categoria, int Id_Pregunta,FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                PreguntaCategoria preguntaCategoria = new PreguntaCategoria(Id_categoria, Id_Pregunta);
                PreguntaCategoriaComponent preguntaCategoriaComponent = new PreguntaCategoriaComponent();
                preguntaCategoriaComponent.Delete(preguntaCategoria);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

Evaluaciones Tecnicas/Controllers/Preguntas y Respuestas/TipoPreguntaController.cs
using Negocio;
using Entities;

using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Evaluaciones_Tecnicas.Filter;

namespace Safari.UI.Web.Controllers
{
   
    public class TipoPreguntaController : Controller
    {

        // GET: TipoPregunta
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [Route("TipoPregunta", Name = "TipoPreguntaControllerRouteIndex")]
        public ActionResult Index()
        {
            TipoPreguntaComponent tipoPregunta = new TipoPreguntaComponent();
          
           
            return View(tipoPregunta.Read());
        }

        // GET: TipoPregunta/Details/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Details(int id)
        {

            TipoPreguntaComponent tipoPregunta = new TipoPreguntaComponent();
            return View(tipoPregunta.ReadBy(id));
        }

        // GET: TipoPregunta/Create
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoPregunta/Create
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                TipoPreguntaComponent tipoPreguntaComponent = new TipoPreguntaComponent();
                TipoPregunta tipoPregunta = new TipoPregunta();
                tipoPregunta.TipoDePregunta = collection.Get("TipoDePregunta");
                tipoPreguntaComponent.Create(tipoPregunta);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoPregunta/Edit/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Edit(int id)
        {
            TipoPreguntaComponent tipoPreguntaComponent = new TipoPreguntaComponent();

            return View(tipoPreguntaComponent.ReadBy(id));

        }

        // POST: TipoPregunta/Edit/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                // TODO: Add update logic here
                TipoPreguntaComponent tipoPreguntaComponent = new TipoPreguntaComponent();
                TipoPregunta tipoPregunta = new TipoPregunta();
                tipoPregunta.TipoDePregunta = collection.Get("TipoDePregunta");
                tipoPregunta.Id = int.Parse(collection.Get("Id"));
                tipoPreguntaComponent.Update(tipoPregunta);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoPregunta/Delete/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        public ActionResult Delete(int id)
        {

            TipoPreguntaComponent tipoPreguntaComponent = new TipoPreguntaComponent();

            return View(tipoPreguntaComponent.ReadBy(id));
        }
        public ActionResult SaludTipoPregunta(int id)
        {
            SaludCategoriaComponent saludCategoriaComponent = new SaludCategoriaComponent(id);
            return View( saludCategoriaComponent.verificarSaludTipoPregunta());


        }
        // POST: TipoPregunta/Delete/5
        [AuthorizerUser(_roles: "Administrador,CrearPregunta,RRHH")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                TipoPreguntaComponent tipoPreguntaComponent = new TipoPreguntaComponent();
                TipoPregunta tipoPregunta = new TipoPregunta();
               
                tipoPregunta.Id = id;
                tipoPreguntaComponent.Delete(id);
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/AgregarCategoria.cshtml
@model Evaluaciones.Models.PreguntaCategoriaModels

@{
    ViewBag.Title = "AgregarCategoria";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}





<link href="~/Content/css/sb-admin-2.css" rel="stylesheet" />







<form method="post" enctype="multipart/form-data">


    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Agregar una categoria a la pregunta <i>"@Html.DisplayFor(model => model.Pregunta)"</i></h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <h5 class="text-justify">Categoria</h5>
                    @Html.DropDownList("Categoria", (SelectList)ViewBag.categoriaLista as SelectList, new { @class = "form-control" })


                </div>


                <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "PreguntaCategoria")'" />

                <br />

                <input type="submit" value="Crear" class="btn btn-outline-info" />

            </div>
        </div>
    </div>
</form>





@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/Categoria.cshtml
@model IEnumerable<Evaluaciones.Models.PreguntaCategoriaModels>

@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">

                        @foreach (var item2 in Model)
                        {
                            <h6>   Pregunta: @Html.DisplayFor(modelItem => item2.Pregunta)</h6>
                            break;
                        }


                    </h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Categoria</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Acciones</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Categoria)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Agregar Categoria", "Create", new { id = item.ID_Pregunta }) |

                                                    @Html.ActionLink("Eliminar categoria", "Delete", new
                                               {
                                                   id_Pregunta = item.ID_Pregunta,
                                                   Id_Categoria = item.ID_Categoria
                                               })

                                                </td>


                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/CategoriaPregunta.cshtml
@model IEnumerable<Entities.Categoria>

@{
    ViewBag.Title = "CategoriaPregunta";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}
<link href="~/Content/modern-business.css" rel="stylesheet" />

<link href="~/Content/modern-business.css" rel="stylesheet" />
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">


        <!-- Begin Page Content -->
        <div class="container-fluid">


            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de categorias</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 103px;">Categoria</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 162px;">Descripcion</th>

                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.LaCategoria)
                                                </td>
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                                </td>



                                            </tr>
                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/Create.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />

@using (Html.BeginForm("create", "creadorPreguntas", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()

    <div class="d-flex flex-column">
        <div class="container-fluid">
            <div class="card shadow mb-4" style="min-width:850px">
                <div class=" card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Crear una pregunta</h6>



                </div>
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <h5 class="text-justify">Pregunta</h5>
                    @Html.EditorFor(model => model.LaPregunta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LaPregunta, "", new { @class = "text-danger" })
                    <br />
                    <h5 class="text-justify">Ubicacion Imagen</h5>

                    @*<input type="file" name="file" accept="image/*" />*@

                    <input type="file" name="File" class="btn btn-outline-primary" /> <br />

                    <br />

                    <h5 class="text-justify">Categoria</h5>

                    @Html.DropDownListFor(model => model.categoria.Id, (SelectList)ViewBag.categoriaLista as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.categoria.Id, "", new { @class = "text-danger" })
                    <br />

                    <h5 class="text-justify">Tipo de pregunta</h5>

                    @Html.DropDownListFor(model => model.tipoPregunta.Id, (SelectList)ViewBag.TipoDePreguntaLista as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tipoPregunta.Id, "", new { @class = "text-danger" })
                    <br />

                    <h5 class="text-justify">Nivel</h5>

                    @Html.DropDownListFor(model => model.nivel.Id, (SelectList)ViewBag.ListaNivel as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.nivel.Id, "", new { @class = "text-danger" })
                    <br />


                </div>


                <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "preguntacategoria")'" />

                <br />

                <input type="submit" value="Crear" class="btn btn-outline-info" />

            </div>
        </div>
    </div>
}


@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/Delete.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}
<link href="~/Content/modern-business.css" rel="stylesheet" />

<div class="table-responsive">
    <h3 class="col-md-10">¿Esta seguro que quiere eliminar la Pregunta @Html.DisplayFor(model => model.Id)? </h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            <input type="button" class="form-actions no-color " style="float:right" value="Volver" onclick="location.href='@Url.Action("PreguntaCategoria", "creadorPreguntas")'" />
            <input type="submit" value="Eliminar" class="btn btn-outline-primary" />
        </div>
    }
</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/Details.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />



<div class="d-flex flex-column">
    <div class="container-fluid">
        <div class="card shadow mb-4">

            <div class=" card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Detalles de La Pregunta  @Html.DisplayFor(model => model.LaPregunta)</h6>

            </div>

            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)






                <h5 class="text-justify">Pregunta</h5>
                @Html.DisplayFor(model => model.LaPregunta)

                <br />
                <br />
                <h5 class="text-justify">Imagen</h5>
                @Html.DisplayFor(model => model.Imagen)
                <br />   <br />
                <h5 class="text-justify">Nivel</h5>

                @Html.DisplayFor(model => model.nivel.ElNivel)

                <br />   <br />
                <h5 class="text-justify">Tipo de pregunta</h5>
                @Html.DisplayFor(model => model.tipoPregunta.TipoDePregunta)
                <br />
            </div>



            <input type="button" class="btn btn-outline-primary " style="float:left" value="Volver" onclick="location.href='@Url.Action("PreguntaCategoria", "CreadorPreguntas")'" />
            <input type="button" class="btn btn-outline-primary " style="float:left" value="Editar" onclick="location.href='@Url.Action("edit", "CreadorPreguntas",new { id = Model.Id })'" />
            <br />
        </div>
    </div>
</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/DetailsSubPregunta.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "DetailsSubPregunta";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />


<div class="d-flex flex-column">
    <div class="container-fluid">
        <div class="card shadow mb-4">

            <div class=" card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Detalles de La Pregunta  @Html.DisplayFor(model => model.LaPregunta)</h6>

            </div>

            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)






                <h5 class="text-justify">Pregunta</h5>
                @Html.DisplayFor(model => model.LaPregunta)

                <br />
                <br />
                <h5 class="text-justify">Imagen</h5>
                @Html.DisplayFor(model => model.Imagen)
                <br />   <br />
                <h5 class="text-justify">Nivel</h5>

                @Html.DisplayFor(model => model.nivel.ElNivel)

                <br />   <br />
                <h5 class="text-justify">Tipo de pregunta</h5>
                @Html.DisplayFor(model => model.tipoPregunta.TipoDePregunta)
                <br />
            </div>



            <input type="button" class="btn btn-outline-primary " style="float:left" value="Volver" onclick="location.href='@Url.Action("Index", "PreguntaCategoria")'" />
            <input type="button" class="btn btn-outline-primary " style="float:left" value="Editar" onclick="location.href='@Url.Action("edit", "Preguntas",new { id = Model.Id })'" />
            <br />
        </div>
    </div>
</div>


@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/ErrorPage.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "ErrorPage";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}
</p>

<link href="~/Content/modern-business.css" rel="stylesheet" />



<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">



        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- 404 Error Text -->
            <div class="text-center">
                <div class="error mx-auto" data-text="Error">Error</div>
                <p class="lead text-gray-800 mb-5">La pregunta o subPregunta <i>" @Html.DisplayFor(model => model.LaPregunta) " ya fue creada por favor cree otra pregunta o modifiqueparte de ella </i></p>
                <p class="text-gray-500 mb-0">Por favor colocar otro nombre</p>
                <a href="@Url.Action("Index", "PreguntaCategoria")">← volver al inicio</a>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>

@section scripts
{
}

Evaluaciones Tecnicas/Views/CreadorPreguntas/QuitarCategoria.cshtml
@model Entities.PreguntaCategoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutCreador.cshtml";
}

<link href="~/Content/modern-business.css" rel="stylesheet" />


<div class="table-responsive">
    <h3>¿Esta seguro de eliminar la categoria <i>"@Html.DisplayFor(model => model.Categorias.LaCategoria)"</i> de la pregunta <i>"@Html.DisplayFor(model => model.Pregunta.LaPregunta)"</i>?</h3>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-outline-info" />

            <input type="button" class="btn btn-outline-primary " style="float:right" value="Volver" onclick="location.href='@Url.Action("Index", "PreguntaCategoria")'" />
        </div>
    }
</div>

@section scripts
{
}